### ISSUE TITLE
PHPDocs incorrect

### ISSUE THREAD

**Issue by MrJmpl3** [lecano/php-numero-a-letras#2]
Using PHPStorm, I saw the PHPDocs are incorrect, for example:

```    
    /**
     * Formatea y ejecuta la función conversora con formato para facturación
     *
     * @param $number número a convertir
     * @param $decimals número de puntos decimales
     * @param $currency nombre de moneda
     * @return void
     */
``` 

In PHPDocs, that mean: $number is a type of "número".

To fix, I recommend add a type of variable in the docs or add mixed instead.

**Comment by lecano** [comment]
PHPDocs updated with [v2.0.1](https://github.com/lecano/php-numero-a-letras/tree/v2.0.1) release.

Feel free to open a PR for further improvement or changes.
