### ISSUE TITLE
Función toMoney

### ISSUE THREAD

**Issue by arce701** [lecano/php-numero-a-letras#3]
Hola, felicitaciones por este excelente paquete, solo quería mostrarte mi caso. 
```
   public static function getTextHas($has)
    {
        $formatter = new NumeroALetras;
        $formatter->apocope = true;
        if (intval($has) == 1) {
            $hasText = 'Hectárea';
        } else {
            $hasText = 'Hectáreas';
        }
        return self::textTitle($formatter->toMoney($has, 4, $hasText, 'Metros Cuadrados'));
    }
```
```
// $has = 2.8567
// Dos Hectáreas Con Ocho Mil Quinientos Sesenta y Siete Metros Cuadrados
```

Uso la función **toMoney**, pero no me siento cómodo con el nombre, talvez otra función más generalizada para hacer este tipo de encadenamientos. 
De nuevo excelente trabajo.

**Comment by lecano** [comment]
Se podría generar un alias a la función, posiblemente toString(), toFormat() o un nombre que puedas sugerir.

**Comment by lecano** [comment]
Se agregó función toString() con la versión 2.1.0
