### ISSUE TITLE
Problemas con tildes

### ISSUE THREAD

**Issue by arce701** [lecano/php-numero-a-letras#4]
**VEINTITRÉS** lleva tilde, entiendo que es la unión de dos partes **TRES**, solo no lleva tilde pero si le unimos con VEINTI, ahora debería llevar tilde. No sé cuantos más de estos casos habrá. Si le parece, podría ser colaborador de este paquete para hacer este tipo de revisiones.

**Comment by lecano** [comment]
En nuestro idioma son cuatro casos con tilde para 16, 22, 23 y 26.

La lógica para 22, 23 y 26 se debe manejar en el ultimo `else` de la función `convertGroup($n)` .

Las colaboraciones son todas bienvenidas, puedes enviar un PR con los cambios para integrarlos al repositorio principal.

**Comment by lecano** [comment]
De momento no se trabajará en esta función, pueden enviar un PR con su solución.
