### ISSUE TITLE
Problema de compatibilidad en Laravel

### ISSUE THREAD

**Issue by JorgRios** [lecano/php-numero-a-letras#7]
Hay alguna forma de que corra en laravel? 
ya q intente implementar el paquete pero  al correr la funcion toWords me manda el siguiente error 

PHP Deprecated:  Non-static method Luecano\NumeroALetras\NumeroALetras::toWords() should not be called statically in C:\xampp\htdocs\test\app\Helpers.php on line 35
PHP Error:  Using $this when not in object context in C:\xampp\htdocs\test\vendor\luecano\numero-a-letras\src\NumeroALetras.php on line 95

a q se deberia o si no podria tratar de aportar en la solucion ya q la compatibilidad podria estar alli para usarlodentro de laravel

estoy usando laravel 8 con php 7.4.29

para q me funcione el Alias de laravel use esto 

'Numero' => Luecano\NumeroALetras\NumeroALetras::class,

la forma en la q estoy invocando la funcion es la siguente:

return Numero::toWords(2022);

**Comment by lecano** [comment]
Hola, actualmente uso la librería con Laravel 7/8/9 en php 7.4 y 8.1 sin problemas de la siguiente forma:

```php
use Luecano\NumeroALetras\NumeroALetras;
$letras = new NumeroALetras;
$letras->toInvoice(100, 2, 'soles')
```
No uso alias.

En releases anteriores a la v2.0.0 se usaba el método estático, te recomiendo verificar que versión estas usando y actualizarla para superar el mensaje de error.

```bash
composer require luecano/numero-a-letras "^3.0"
```

**Comment by JorgRios** [comment]
> Hola, actualmente uso la librería con Laravel 7/8/9 en php 7.4 y 8.1 sin problemas de la siguiente forma:
> 
> ```
> use Luecano\NumeroALetras\NumeroALetras;
> $letras = new NumeroALetras;
> $letras->toInvoice(100, 2, 'soles')
> ```
> 
> No uso alias.
> 
> En releases anteriores a la v2.0.0 se usaba el método estático, te recomiendo verificar que versión estas usando y actualizarla para superar el mensaje de error.
> 
> ```shell
> composer require luecano/numero-a-letras "^3.0"
> ```

ok, me hubiera parecido interesante la forma de llamar a todo bajo un alias pero de todas formas es funcionanal como indicas, si me lo permites vere si puedo hacer unas modificaciones para ese soporte de alias, solo por los loles.
y gracias por la respuessta inmediata, un saludo
